[features]
seeds = false
skip-lint = false

[programs.localnet]
token_swap_program = "CkDEBSt52MZaHatWguaDb8qaSmcbv1H6cbAP8Jc1tRjK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/stillo/my-solana-wallet/mykeypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
